workflows:
  expo_scenesnitch:
    name: SceneSnitch • Expo (Android + iOS)
    environment:
      node: 20
      xcode: latest
      groups:
        - scenesnitch_env     # your secure env group in Codemagic
      vars:
        EXPO_CLI_VERSION: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    scripts:
      - name: Install deps
        script: npm ci || npm i
      - name: Verify env keys are present
        script: |
          echo "EXPO_PUBLIC_GOOGLE_MAPS_API_KEY=${EXPO_PUBLIC_GOOGLE_MAPS_API_KEY:0:4}****"
          echo "TMDB_API_KEY=${TMDB_API_KEY:+set}"
          echo "FIREBASE_API_KEY=${FIREBASE_API_KEY:+set}"
      - name: Expo Doctor
        script: npx expo-doctor || true


      - name: Install EAS CLI
        script: npm i -g eas-cli
      - name: EAS build (Android AAB)
        script: npx eas build --platform android --profile preview --non-interactive
      - name: EAS build (iOS)
        script: npx eas build --platform ios --profile preview --non-interactive

    artifacts:

      - dist/**

    publishing:
      email:
        recipients:
          - support@integrityfirstcyber.com
        notify:
          success: true
          failure: true
